version: "3.8"

services:
  vue-app:
    build: .
    container_name: vue-docker
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
